language: node_js
node_js:
  - stable
services:
  - docker
install:
  - npm install
script:
  - npm run test
env:
  global:
    - NEO4J_CONNECTION_URL=bolt://localhost:7687
    - NEO4J_USERNAME=neo4j
    - NEO4J_PASSWORD=password
