language: node_js
notifications:
  slack: theselftalk:EHiDWYYgq34Y172TrHTqA16W
node_js:
  - stable
services:
  - docker
before_script:
  - sudo apt-get install -y realpath
  - docker-compose up --build -d
install:
  - npm install
script:
  - npm run test
after_script:
  - docker-compose logs graphdb_test
env:
  global:
    - NEO4J_BOLT_CONNECTION_URL=bolt://localhost:7687
    - NEO4J_HTTP_CONNECTION_URL=http://localhost:7474
    - NEO4J_USERNAME=neo4j
    - NEO4J_PASSWORD=password
